Stadt=function(){
		this.id;
		this.Leute;
		this.Geld;
		this.Nahrung;
		this.ReparierKurs;
		this.KaufKurs;
		this.Kaffee;
		this.Tabak;
		this.Zuckerrohr;
		this.Rum;
		this.Baumwolle;
		this.Perlen;
		this.Segeltuch;
		this.Hanf;
		this.Teer;
		this.Holz;
		this.Pulver;
		this.Kugeln;
		this.Kanonen;
	}
	Ware=function(){
		this.id;
		this.gewicht;
		this.menge
		
	}
var IschtukAnheuernCounter=0;
var MaximalLadung=10000;
var MaximalGeschwindigkeit=0.4;
var ServiceWert=0;
var SchiffZustand=0;
	Ischtuk=new Stadt();
	Ischtuk.id='Ischtuk';
	Ischtuk.Leute=200;
	Ischtuk.Geld=1734;
	Ischtuk.Nahrung=1545;
	Ischtuk.ReparierKurs=5;
	Ischtuk.KaufKurs=5;
	Ischtuk.Kaffee=5;
	Ischtuk.Tabak=4;
	Ischtuk.Zuckerrohr=4;
	Ischtuk.Rum=32;
	Ischtuk.Baumwolle=2;
	Ischtuk.Perlen=356;
	Ischtuk.Segeltuch=9;
	Ischtuk.Hanf=4;
	Ischtuk.Teer=20;
	Ischtuk.Holz=23;
	Ischtuk.Pulver=50;
	Ischtuk.Kugeln=60;
	Ischtuk.Kanonen=414;
	IschtukPreise=new Ware();
	IschtukPreise.id='IschtukPreise';
	IschtukPreise.Name='Preise';
	IschtukPreise.Nahrung=15;
	IschtukPreise.Kaffee=15;
	IschtukPreise.Tabak=14;
	IschtukPreise.Zuckerrohr=14;
	IschtukPreise.Rum=32;
	IschtukPreise.Baumwolle=12;
	IschtukPreise.Perlen=356;
	IschtukPreise.Segeltuch=9;
	IschtukPreise.Hanf=4;
	IschtukPreise.Teer=20;
	IschtukPreise.Holz=23;
	IschtukPreise.Pulver=50;
	IschtukPreise.Kugeln=60;
	IschtukPreise.Kanonen=414;
	IschtukGewicht=new Ware();
	IschtukGewicht.id='IschtukGewicht';
	IschtukGewicht.Name='Gewicht';
	IschtukGewicht.Nahrung=5;
	IschtukGewicht.Kaffee=5;
	IschtukGewicht.Tabak=5;
	IschtukGewicht.Zuckerrohr=5;
	IschtukGewicht.Rum=5;
	IschtukGewicht.Baumwolle=5;
	IschtukGewicht.Perlen=1;
	IschtukGewicht.Segeltuch=10;
	IschtukGewicht.Hanf=4;
	IschtukGewicht.Teer=10;
	IschtukGewicht.Holz=10;
	IschtukGewicht.Pulver=50;
	IschtukGewicht.Kugeln=50;
	IschtukGewicht.Kanonen=200;