var $=function(id){ return document.getElementById(id); };
var dc=function(tag){ return document.createElement(tag); };

isFollowing=function(who,whom){//Who=wer Folgt;whom=wem wird Gefolgt
if(who.xActual<whom.xActual){
who.xActual+=who.moveSpeed*who.speed;
}
if(who.xActual>whom.xActual){
who.xActual-=who.moveSpeed*who.speed;
}
if(who.yActual<whom.yActual){
who.yActual+=who.moveSpeed*who.speed;
}
if(who.yActual>whom.yActual){
who.yActual-=who.moveSpeed*who.speed;
}
if(who.isPassing(0)){
if(who.xActual>whom.xActual){
who.xActual+=who.moveSpeed*who.speed;
}
if(who.xActual<whom.xActual){
who.xActual-=who.moveSpeed*who.speed;
}
if(who.yActual>whom.yActual){
who.yActual+=who.moveSpeed*who.speed;
}
if(who.yActual<whom.yActual){
who.yActual-=who.moveSpeed*who.speed;
}
}
}
isEscaping=function(who,whom){//Who=wer Folgt;whom=wem wird Gefolgt
if(who.xActual>whom.xActual){
who.xActual+=who.moveSpeed*who.speed;
}
if(who.xActual<whom.xActual){
who.xActual-=who.moveSpeed*who.speed;
}
if(who.yActual>whom.yActual){
who.yActual+=who.moveSpeed*who.speed;
}
if(who.yActual<whom.yActual){
who.yActual-=who.moveSpeed*who.speed;
}
if(who.isPassing(0)){
if(who.xActual>whom.xActual){
who.xActual+=who.moveSpeed*who.speed;
}
if(who.xActual<whom.xActual){
who.xActual-=who.moveSpeed*who.speed;
}
if(who.yActual>whom.yActual){
who.yActual+=who.moveSpeed*who.speed;
}
if(who.yActual<whom.yActual){
who.yActual-=who.moveSpeed*who.speed;
}
}
}